### PR TITLE
Add example in the CI testsuite #43

### LINKED ISSUE #43: Run the example in the test suite to verify that it actually runs

### PR DESCRIPTION
**Pull request by blackheaven**
# Description

Please include a summary of the change and which issue is fixed.

Fixes #43

# Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added changes to the relevant changelog
- [ ] I have made corresponding changes to the documentation
- [ ] I have added haddock comments for every new function and data

Not sure this list is relevant, I can add dedicated tests if you have ideas.

### CODE REVIEW

**Comment by ludat** [comment]
Hi thanks for the PR

There is something missing though, if you look closely the `stack-ci.yaml` is not used if there is a more specific environment, for example for lts 16.12 on windows [stack-lts-16.12-windows.yaml](https://github.com/ludat/conferer/blob/master/stack-lts-16.12-windows.yaml) is used instead of stack-ci.yaml.

**Comment by blackheaven** [comment]
Here we go! :)

**Comment by blackheaven** [comment]
Are we sure we want to stay compatible with GHC 8.2.2?

**Comment by ludat** [comment]
yeah, it's from 2017 so I'm fine if we stop building it in CI, do you mind removing it from the CI?

**Comment by blackheaven** [comment]
Done, and I have rebased

**Pull request merged**
